### ISSUE TITLE
Some menu items have a white background in dark mode

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#1341]
It would be nice if they had a black background, too.

![IMG_0430](https://user-images.githubusercontent.com/28911/212468751-1f72a481-6cd7-4d21-8d02-de7eed59e06f.jpeg)

**Comment by wkillerud** [comment]
There is a dark version of the dropdown in Bootstrap, but it works by setting a class in the HTML which means it's set for both light and dark mode. 

We could apply the dark style CSS ourselves with a local override only if `prefers-color-scheme` is `dark`. However, proper [dark mode support is coming to Bootstrap in version 5.3.0](https://blog.getbootstrap.com/2022/12/24/bootstrap-5-3-0-alpha1/), which hopefully will make it easier to switch between light and dark here (and also for the input fields).

**Comment by ujh** [comment]
Ah, and I guess now we can keep up to date more easily. Great, let's just close it for now. It's a very minor annoyance anyway. There's bigger fish to fry!
