### ISSUE TITLE
Allow users to hide columns in the inks table

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#1365]
The tables are pretty wide and there's already code in place to hide columns when there's no data in any of them. I recently had the request for hiding some of the data and it might be worth looking into letting users pick which columns to hide, e.g. someone wanted to hide the "usage" and "daily usage" columns.

**Comment by wkillerud** [comment]
We can build on the same setup as for card vs table layout, and use [localhost to store preferences](https://github.com/ujh/fountainpencompanion/blob/8aa72f177d980725ea8ccaf6361ed308f83feb79/app/javascript/src/collected_inks/index.jsx#L49-L58).

There's the option of small [forms in dropdowns](https://getbootstrap.com/docs/5.3/components/dropdowns/#forms), for instance a list of switches.

I made a small demo of how it could look with a [settings-dropdown for the table view](https://codesandbox.io/s/romantic-galileo-n4vrhn?file=/src/App.js). The same settings _can_ be used also in the card view if we'd like. Another option is to hide the settings dropdown for the card view.

**Comment by ujh** [comment]
Oh, I like that. I have nothing against doing the same in the card view, too, if it's simpler.
