### ISSUE TITLE
Make it easier to notice when the table is wider than the page

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#1366]
With the redesign, when the inks table is wider than the browser window it is hard to notice that there is more content to the right as it's just the table that has the scroll bar (and only at the bottom) instead of the whole window having the scroll bar.

It would be nice to somehow show the users that there's more to the right, especially as all the buttons are on the right side.

**Comment by ujh** [comment]
If you have any idea, @wkillerud. ;)

**Comment by wkillerud** [comment]
Hmm, good point. My first thought is to maybe add [scroll shadows](https://codepen.io/mrowa44/pen/xRpMYm). We could also undo the scroll behavior and have full-page scroll like before.

**Comment by ujh** [comment]
The scroll shadow does sound like a good idea.
