### ISSUE TITLE
swab in currently inked missing

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#1374]
The swab used for the mobile display of the currently inked page is missing. When debugging it, it seems that webpack somehow doesn't produce a proper SVG file that we can link against. I also wasn't able to use the `url-loader` get it inlined into the CSS. I am not sure what's happening here.

If you have any ideas @wkillerud it would be much appreciated.

**Comment by wkillerud** [comment]
I'll take a look

**Comment by ujh** [comment]
💚
