### ISSUE TITLE
Add ESLint to CI

### ISSUE THREAD

**Issue by wkillerud** [ujh/fountainpencompanion#1380]
As mentioned in #1377, add ESLint with the recommended rules and run it on CI and pre-commit.

- [`eslint:recommended`](https://eslint.org/docs/latest/rules)
- [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier)

For React projects I also usually add:
- [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks) warns when a hook might end up with stale data (missing things in the deps array).
- [`eslint-plugin-react`](https://www.npmjs.com/package/eslint-plugin-react), but with the `prop-types` rule turned off.

We probably also have to add some [environment-config for Jest](https://eslint.org/docs/latest/use/configure/language-options#specifying-environments)

Example config:

```json
{
    "plugins": ["prettier", "react", "react-hooks"],
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:react-hooks/recommended"
    ],
    "rules": {
        "react/prop-types": "off",
        "prettier/prettier": "error",
        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "error"
    }
}
```

**Comment by ujh** [comment]
Whatever you think is best. :)
