### ISSUE TITLE
Issues with Dark mode 

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#1414]
In dark mode in Safari (both Mac and iOS) the inks page looks like this:

<img width="1420" alt="Screenshot 2023-02-02 at 21 44 56" src="https://user-images.githubusercontent.com/28911/216445627-9181528d-7b09-4aa3-9be5-06d750fbad30.png">

The titles of the widgets don't look much better:
<img width="1378" alt="Screenshot 2023-02-02 at 21 46 22" src="https://user-images.githubusercontent.com/28911/216445720-d185586a-79a7-45b1-bcb2-bb5a70a644ff.png">

The pens and currently inked sections also don't show any text.

FYI, @wkillerud

**Comment by ujh** [comment]
Actually, dark mode in Firefox is also broken. So at least it doesn't seem to be browser dependent.

**Comment by wkillerud** [comment]
I'll take a look tomorrow to see if I can find the cause

**Comment by ujh** [comment]
Thank you! 💚

**Comment by wkillerud** [comment]
Looks like the collected inks cards in dark mode are bugged now 😅 I’ll do another pass and test more thoroughly.
