### ISSUE TITLE
FPC and self-host

### ISSUE THREAD

**Issue by bmp** [ujh/fountainpencompanion#1698]
Hello,

Thank you for making this available. I have a few questions,
1) Is https://www.fountainpencompanion.com/ active? The last blog entry I found was from January 2021.
2) Can I export my data from the website to a CSV or any such other machine-readable form currently?
3) Can this be used to self-host? Additionally, can I make it a single-user instance (The reason I ask is I'd like to remove things like leaderboard)?
4) When I take a look at https://www.fountainpencompanion.com/users, I am unable to find a listing of pens for any users? Is that intentional and is it meant to be private? If so, can the list of inks be private too?

Thank you!

**Comment by ujh** [comment]
> Hello,
> 
> Thank you for making this available. I have a few questions,
> 
>     1. Is https://www.fountainpencompanion.com/ active? The last blog entry I found was from January 2021.


Yes, the site is still actively developed and has now almost 5000 users that store over 300,000 inks in the system.

>     2. Can I export my data from the website to a CSV or any such other machine-readable form currently?

Yes. All data can be exported as CSV. I don't believe in locking people in. :)

>     3. Can this be used to self-host? Additionally, can I make it a single-user instance (The reason I ask is I'd like to remove things like leaderboard)?

Sure, it's just a Rails project, nothing fancy. You _could_ self host it, but you're loosing on the community features. You can add inks from the global community list (`/brands`) and you already get the color of the ink filled in for free. Comparing your collection with other users (for ink swaps) also only works here, etc. More community features to come in the future.

>     4. When I take a look at https://www.fountainpencompanion.com/users, I am unable to find a listing of pens for any users? Is that intentional and is it meant to be private? If so, can the list of inks be private too?

Yes, the list of pens ins private intentionally (as stated on top when you're on that page) as I don't want publicly available lists of expensive pens. And while the default for inks is that they are public, each entry can also be made private.

**Comment by bmp** [comment]
Thank you for the detailed response! I'll give it a try this week and report back.
