### ISSUE TITLE
Finding inks with similar colors

### ISSUE THREAD

**Issue by Ser5** [ujh/fountainpencompanion#2379]
Hi! Recently I parsed data from [this page](https://www.fountainpencompanion.com/pages/inks_by_popularity) and every ink listed there to create local page, where I can search for inks with similar colors. Shortly after I made my little page [available to everyone](https://www.reddit.com/r/fountainpens/comments/1fe3nz2/yet_another_tool_to_find_inks_with_similar_colors/).

Then I found this repository. And thought that it may be logical if your own big site can use my functionality. If you wish to use my code - [grab it here](https://github.com/Ser5/fpi-closest-colors), it's supersimple.

**Comment by ujh** [comment]
Hey! That's a really cool page and having a page with all public inks like that seems like a good idea, that's true. I do have a color sort for the private data already, so it wouldn't be a bad idea to make this look similar as well. Thanks, I'll keep that in mind whenever I get around to working on that page!
