### ISSUE TITLE
Update pagination on change instead of blur for up/down press?

### ISSUE THREAD

**Issue by nadavspi** [ujh/fountainpencompanion#373]
After focusing on the page jump input, consider immediately updating the table on a up/down key press (or a click on the browser-provided up/down buttons) instead of waiting for blur.

**Comment by ujh** [comment]
Hi Nadav, wow my first Github issue! 🎉 

I'm a bit unsure what exactly you're talking about though. Do you mean my [ugly hack here](https://github.com/ujh/fountainpencompanion/blob/master/app/views/layouts/application.html.slim#L18) or are you talking about the inks React app? Both are most likely going to go away soon anyway. Especially the inks app is super slow and badly designed, plus it doesn't really work on mobile anyway.

**Comment by nadavspi** [comment]
Sorry, I mean in the React app. 

Looking at https://www.fountainpencompanion.com/users/242 as an example:
![Nov-15-2019 09-38-07](https://user-images.githubusercontent.com/4383327/68951277-b367e300-078b-11ea-8323-fc20fdc6ee47.gif)

**Comment by ujh** [comment]
Ah, I see. Yes, that makes total sense. I use a table component and I'm surprised that it doesn't automatically do that. It shouldn't be too hard to get that to work.
