### ISSUE TITLE
Figure out why the build sometimes fails

### ISSUE THREAD

**Issue by ujh** [ujh/fountainpencompanion#40]
Sometimes the travis build fails (some data not in the DB) and on a rerun it suddenly works again.

**Comment by ujh** [comment]
Here's an example: https://travis-ci.org/ujh/fountainpencompanion/builds/371037251

**Comment by valthon** [comment]
I changed the `:save` to a `:save!` in the before function for `./spec/controllers/brands_controller_spec.rb`.  This revealed that (for an empty database) trying to save the `CollectedInk` fails validation (`User must exist`).  Adding `:users` to the `fixtures` call makes it happy.

**Comment by valthon** [comment]
Are you very attached to using Fixtures, or would you accept a pull request to switch over to [factory_bot](https://github.com/thoughtbot/factory_bot)?  I find testing is _much_ cleaner with something that generates records dynamically.

**Comment by ujh** [comment]
Duh! Yeah, seems obvious now. I haven't used fixtures in years so I guess that's where this is coming from. I prefer factory_bot as well, I just haven't gotten around to switching. So yeah, a PR would be accepted!
