### ISSUE TITLE
ability to change the avatar

### ISSUE THREAD

**Issue by KillSession** [ujh/fountainpencompanion#729]
it seems, there is no way to change the avatar in an account of a user, it would be great for users to be able to do so.

**Comment by ujh** [comment]
Hi @KillSession, yes and no. There's currently no way to change the avatar directly on the site (that's coming). However, if you change your avatar on gravatar.com it will be used on FPC as well.

And thank you for opening the issue!

**Comment by ujh** [comment]
See also #31.
